### ISSUE TITLE
Passing a file to the cli without a -loadTest crashes the program.

### ISSUE THREAD

**Issue by marwing** [mattulbrich/mimaflux#3]
Sample Program:
```asm
HALT
```

### Current output:
```
Cannot invoke "String.lastIndexOf(int)" because "loadTest" is null
```

### Expected output:
GUI oens and loads file, or (with -run):
```
        IAR  = 0x000000 =        0              (instruction there: HALT)
        ACCU = 0x000000 =        0
```

**Comment by mattulbrich** [comment]
Thanks for reporting!

Just to make sure: It is the current development version that crashes. The JAR release does not suffer from this flaw.

**Comment by marwing** [comment]
The latest release doesn't suffer from this yet. This is a regression after 19ec283.
